deploy:
  provider: releases
  api_key: $apikey
  skip_cleanup: true
  file_glob: true
  file:
    - "/home/travis/build/libs/NTCore-*-shaded.jar"
    - "/home/travis/build/libs/NTCore-*-sources.jar"
  on:
    branch: release
language: java
jdk:
  - oraclejdk8
after_success:
  - git config --global user.name "Travis CI"
  - export PVERSION="$(cat build.gradle | grep -E "version+ =+ '([^\s]+)'" | awk -F \' '{print $2}')"
  - git tag $GIT_TAG -a -m "$PVERSION"
  - git push origin $PVERSION
